---
dist: bionic
language: node_js
node_js: '10.16'

sudo: required

services:
- docker
#- mongodb

env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
    - ROCKET_CHAT_URI=http://localhost:5000
cache:
  directories:
  - node_modules
  - travis_phantomjs

before_install:
- openssl aes-256-cbc -K $encrypted_2709882c490b_key -iv $encrypted_2709882c490b_iv -in travis_rsa.enc -out travis_rsa -d
- curl https://raw.githubusercontent.com/schul-cloud/schulcloud-authorization-server/master/docker-compose-test.yml > docker-compose-oauthserver.yml
- curl https://raw.githubusercontent.com/schul-cloud/schulcloud-authorization-server/master/.env.example > .env
- sudo docker-compose -f docker-compose-oauthserver.yml up -d
- sudo docker pull mongo:4.0
- sudo docker run -d -p 27017:27017 mongo:4.0
script:
#- pwd
- npm test
- npm run coverage-codecov
#- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
   all_branches: true
#   condition: $TRAVIS_BRANCH =~ ^development|N21/merge$
