dist: bionic
language: node_js
node_js: '10.16'

services:
  - docker

jobs: 
  include:

    - stage: test
      name: test:mocha
      env:
        - ROCKET_CHAT_URI=http://localhost:5000
      cache: npm
      install:
        - curl https://raw.githubusercontent.com/schul-cloud/schulcloud-authorization-server/master/docker-compose-test.yml > docker-compose-oauthserver.yml
        - curl https://raw.githubusercontent.com/schul-cloud/schulcloud-authorization-server/master/.env.example > .env
        - sudo docker-compose -f docker-compose-oauthserver.yml up -d
        - sudo docker pull mongo:4.0
        - sudo docker run -d -p 27017:27017 mongo:4.0
        - npm ci
        - npm i -g wait-on
        - wait-on tcp:27017 -t 60000
      script:
        - npm test
        - npm run coverage-codecov

    - stage: deploy
      name: deploy
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      install:
        - openssl aes-256-cbc -K $encrypted_2709882c490b_key -iv $encrypted_2709882c490b_iv -in travis_rsa.enc -out travis_rsa -d
      script:
        - ./deploy.sh
