name: Migrations updated

on: [push]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install  
      uses: actions/setup-node@v1
      run: npm ci
    - name: all migrations are added to database
      run: npm run migration-list    
    - name: all migrations from database exist in filesystem
      run: npm run migration-prune
    - name: migration collection is up to date
      run: npm run migration-persist
      run: git status backup/**
