name: Migrations updated

on: [push]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install  
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run migration-list    
    - run: npm run migration-prune
    - run: npm run migration-persist
    - run: git status backup/**
