name: Database seed changes & format

on: [push]

jobs:
  migration:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: check all migrations are up in database seed
        run: test $(grep "\"down\"" ./backup/setup/migrations.json -c) -eq 0
      - uses: actions/checkout@v2
      - name: check all migrations are up in database seed
        run: test $(grep "\"down\"" ./backup/setup/migrations.json -c) -eq 0
      - name: mongodb setup
        uses: supercharge/mongodb-github-action@1.3.0
      - name: setup
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run setup
      - name: check formatting of database seed files in backup/**
        run: |
          npm run backup-setup
          git diff --exit-code backup/**
